//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naves {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naves.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcance.
        /// </summary>
        internal static string Alcance {
            get {
                return ResourceManager.GetString("Alcance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daño por llegar a la salida (y por chocar).
        /// </summary>
        internal static string Ataque_Enemigo {
            get {
                return ResourceManager.GetString("Ataque_Enemigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daño ocasionado (y daño antiaereo).
        /// </summary>
        internal static string Ataque_Nave {
            get {
                return ResourceManager.GetString("Ataque_Nave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daño ocasionado.
        /// </summary>
        internal static string Ataque_Torre {
            get {
                return ResourceManager.GetString("Ataque_Torre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        internal static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        internal static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu\\boton_vender_01.
        /// </summary>
        internal static string Boton_Sell {
            get {
                return ResourceManager.GetString("Boton_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu\\boton_mejorar_01.
        /// </summary>
        internal static string Boton_Upgrade {
            get {
                return ResourceManager.GetString("Boton_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completado.
        /// </summary>
        internal static string Completado {
            get {
                return ResourceManager.GetString("Completado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar Partida.
        /// </summary>
        internal static string Continuar_Partida {
            get {
                return ResourceManager.GetString("Continuar_Partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daño.
        /// </summary>
        internal static string Daño {
            get {
                return ResourceManager.GetString("Daño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daño antiarereo.
        /// </summary>
        internal static string Daño_antiaereo {
            get {
                return ResourceManager.GetString("Daño_antiaereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero.
        /// </summary>
        internal static string Dinero {
            get {
                return ResourceManager.GetString("Dinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a disparo.
        /// </summary>
        internal static string disparo {
            get {
                return ResourceManager.GetString("disparo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CazaMercurio.
        /// </summary>
        internal static string Enemigo_CazaMercurio {
            get {
                return ResourceManager.GetString("Enemigo_CazaMercurio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garras.
        /// </summary>
        internal static string Enemigo_Garras {
            get {
                return ResourceManager.GetString("Enemigo_Garras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Helicoptero.
        /// </summary>
        internal static string Enemigo_Helicoptero {
            get {
                return ResourceManager.GetString("Enemigo_Helicoptero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Robot.
        /// </summary>
        internal static string Enemigo_Robot {
            get {
                return ResourceManager.GetString("Enemigo_Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tanque.
        /// </summary>
        internal static string Enemigo_Tanque {
            get {
                return ResourceManager.GetString("Enemigo_Tanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganas.
        /// </summary>
        internal static string Ganas {
            get {
                return ResourceManager.GetString("Ganas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inactivo.
        /// </summary>
        internal static string inactivo {
            get {
                return ResourceManager.GetString("inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jupiter.
        /// </summary>
        internal static string Jupiter {
            get {
                return ResourceManager.GetString("Jupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Laser.
        /// </summary>
        internal static string Laser {
            get {
                return ResourceManager.GetString("Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marte.
        /// </summary>
        internal static string Marte {
            get {
                return ResourceManager.GetString("Marte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejorar.
        /// </summary>
        internal static string Mejorar {
            get {
                return ResourceManager.GetString("Mejorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Principal.
        /// </summary>
        internal static string Menu_Principal {
            get {
                return ResourceManager.GetString("Menu_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercurio.
        /// </summary>
        internal static string Mercurio {
            get {
                return ResourceManager.GetString("Mercurio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misiles.
        /// </summary>
        internal static string Misiles {
            get {
                return ResourceManager.GetString("Misiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple.
        /// </summary>
        internal static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nave.
        /// </summary>
        internal static string Nave {
            get {
                return ResourceManager.GetString("Nave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neptuno.
        /// </summary>
        internal static string Neptuno {
            get {
                return ResourceManager.GetString("Neptuno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nivel.
        /// </summary>
        internal static string nivel {
            get {
                return ResourceManager.GetString("nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Partida.
        /// </summary>
        internal static string Nueva_Partida {
            get {
                return ResourceManager.GetString("Nueva_Partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de disparos.
        /// </summary>
        internal static string Numero_disparos {
            get {
                return ResourceManager.GetString("Numero_disparos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planeta.
        /// </summary>
        internal static string Planeta {
            get {
                return ResourceManager.GetString("Planeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero que recibes si lo matas.
        /// </summary>
        internal static string Precio_Enemigo {
            get {
                return ResourceManager.GetString("Precio_Enemigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        internal static string Puntos {
            get {
                return ResourceManager.GetString("Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia de disparo.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rayo.
        /// </summary>
        internal static string Rayo {
            get {
                return ResourceManager.GetString("Rayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saturno.
        /// </summary>
        internal static string Saturno {
            get {
                return ResourceManager.GetString("Saturno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vender torre.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Completar.
        /// </summary>
        internal static string Sin_Completar {
            get {
                return ResourceManager.GetString("Sin_Completar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        internal static string Sonido {
            get {
                return ResourceManager.GetString("Sonido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo para la siguiente oleada.
        /// </summary>
        internal static string Tiempo {
            get {
                return ResourceManager.GetString("Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tierra.
        /// </summary>
        internal static string Tierra {
            get {
                return ResourceManager.GetString("Tierra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torre.
        /// </summary>
        internal static string Torre {
            get {
                return ResourceManager.GetString("Torre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antiaerea.
        /// </summary>
        internal static string Torre_AntiAire {
            get {
                return ResourceManager.GetString("Torre_AntiAire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloque.
        /// </summary>
        internal static string Torre_Bloque {
            get {
                return ResourceManager.GetString("Torre_Bloque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canon.
        /// </summary>
        internal static string Torre_Canon {
            get {
                return ResourceManager.GetString("Torre_Canon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hielo.
        /// </summary>
        internal static string Torre_Hielo {
            get {
                return ResourceManager.GetString("Torre_Hielo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tanque.
        /// </summary>
        internal static string Torre_Tanque {
            get {
                return ResourceManager.GetString("Torre_Tanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triple.
        /// </summary>
        internal static string Torre_Triple {
            get {
                return ResourceManager.GetString("Torre_Triple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urano.
        /// </summary>
        internal static string Urano {
            get {
                return ResourceManager.GetString("Urano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad.
        /// </summary>
        internal static string Velocidad {
            get {
                return ResourceManager.GetString("Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venus.
        /// </summary>
        internal static string Venus {
            get {
                return ResourceManager.GetString("Venus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vida restante (y total).
        /// </summary>
        internal static string Vida {
            get {
                return ResourceManager.GetString("Vida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vida.
        /// </summary>
        internal static string Vida_Nave {
            get {
                return ResourceManager.GetString("Vida_Nave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen FX.
        /// </summary>
        internal static string Volumen_FX {
            get {
                return ResourceManager.GetString("Volumen_FX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen Musica.
        /// </summary>
        internal static string Volumen_Musica {
            get {
                return ResourceManager.GetString("Volumen_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oleada.
        /// </summary>
        internal static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oleada de enemigos.
        /// </summary>
        internal static string Wave_Tooltip {
            get {
                return ResourceManager.GetString("Wave_Tooltip", resourceCulture);
            }
        }
    }
}
